<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GolfClubTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clubs = [
            'Allanridge Golf Club',
            'Amphitheatre Golf Club',
            'Albertinia Golf Club',
            'Aberdeen Golf Club',
            'Alexandria Golf Club',
            'Amandelbult Golf Club',
            'Arendskraal Golf Club',
            'Atlantic Beach Golf Club',
            'Afrikander Golf Club',
            'Arnot Golf Club',
            'Amersfoort Golf Club',
            'Amatikulu Country Club',
            'Amanzimtoti Country Club',
            'Akasia Country Club',
            'Adelaide Golf Club',
            'Avion Park Golf Club',
            'Aliwal North Golf Club',
            'Alexander Golf Club',
            'Arabella Country Estate',
            'Black Mountain Golf Club',
            'Beaufort West Golf Club',
            'Bosch Hoek Golf Club',
            'Blyvooruitzicht Golf Club',
            'Bloemhof Golf Club',
            'Beeshoek Golf Club',
            'Black Rock Golf Club',
            'Bank Golf Club',
            'Bellville Golf Club',
            'Boggomsbaai Golf Club',
            'Bethal Golf Club',
            'Belfast Golf Club',
            'Barberton Golf Club',
            'Badplaas Golf Club, Guest House and Lodge',
            'Bluff National Park Golf Club',
            'Bronkhorstspruit Golf Club',
            'Blue Valley Golf and Country Estate',
            'Blair Atholl',
            'Bloemfontein Golf Club',
            'Bultfontein Golf Club',
            'Brandfort Golf Club',
            'Bothaville Golf Club',
            'Bethlehem Golf Club',
            'Bethulie Golf Club',
            'Bushman Sands Golf Club',
            'Bedford Golf Club',
            'Benoni Country Club',
            'Bryanston Country Club',
            'Butterworth Country Club',
            'Burgersdorp Golf Club',
            'Barkly East Golf Club',
            'Bredasdorp Golf Club',
            'Bonnievale Golf Club',
            'Berg Rivier Golf Club',
            'Chrome Golf Club',
            'Colesberg Golf Club',
            'Cathcart Golf Club',
            'Carnarvon Golf Club',
            'Creighton Golf Estate',
            'Christiana Golf Club',
            'Calvinia Golf Club',
            'Cmr Golf Club',
            'Cathedral Peak Golf Club',
            'Crocodile Golf Course',
            'Carolina Golf Club',
            'Clovelly Country Club',
            'Cotswold Downs',
            'Champagne Sports Resort',
            'Cato Ridge Country Club',
            'Camelot Country Club',
            'Cullinan Golf Club',
            'Centurion Country Club',
            'Clocolan Golf Club',
            'Clarens Golf and Trout Estate',
            'Cradock Golf Club',
            'Crown Mines Golf Club',
            'Clanwilliam Golf Club',
            'Citrusdal Golf Club',
            'Ceres Golf Club',
            'Caledon Golf Club',
            'Dunblane Golf and Trout Estate',
            'Dewetsdorp Golf Club',
            'Darling Golf Club',
            'de Hoek Golf Club',
            'de Aar Country Club',
            'Douglas Golf Club',
            'Durbanville Golf Club',
            'De Zalze Golf Club',
            'Dolphin Creek Golf Estate',
            'Delareyville Golf Club',
            'Drakensig Golf Club',
            'Durban Country Club',
            'Dundee Country Club',
            'Darnall Country Club',
            'Durban Golf Club',
            'Delmas Golf Club',
            'Daveyton Golf Club',
            'Durban Deep Golf Club',
            'Dainfern Country Club',
            'Dordrecht Golf Club',
            'Devonvale Golf and Wine Estate',
            'Eureka Golf Club',
            'Edenburg Golf Club',
            'Eagles Creek Golf and Nature Estate',
            'Excelsior Golf Club',
            'Erinvale Golf Club',
            'Euphoria Golf and Lifestyle Estate',
            'Elements Private Golf Reserve',
            'Ermelo Country Club',
            'Estcourt Golf Club',
            'Eshowe Hills Eco Estate',
            'Empangeni Country Club',
            'Els Club - Copperleaf',
            'Erpm Golf Club',
            'Engineers Golf Club',
            'Ebotse Golf and Country Estate',
            'Eye of Africa Golf Estate',
            'Emfuleni Golf Estate',
            'Eagle Canyon Country Club',
            'Elliot Golf Club',
            'East London Golf Club',
            'Fairview Golf Estate',
            'Frankfort Golf Club',
            'Fish River Sun Hotel and Country Club Resort',
            'Fort Beaufort Golf Club',
            'Fynbos Golf and Country Estate',
            'Glengarry Country Club',
            'Groblersdal Golf Club',
            'Glendower Golf Club',
            'Germiston Golf Club',
            'Gary Player Country Club',
            'Goose Valley Golf Club',
            'George Golf Club',
            'Greenside Colliery Golf Club',
            'Graceland Country Club',
            'Greytown Country Club',
            'Gowrie Farm Golf Club',
            'Glencoe Correctional Services Golf Club',
            'Grahamstown Golf Club',
            'Graaff Reinet Golf Club',
            'Goldfields West Golf Club',
            'Glenvista Country Club',
            'Gonubie Golf Club',
            'Gansbaai Golf Club',
            'Hopetown Golf Club',
            'Heron Banks Golf and River Estate',
            'Heilbron Country Club',
            'Hotazel Golf Club',
            'Hillside Golf Club',
            'Harding Golf Club',
            'Heidelberg Country Club',
            'Hartswater Golf Club',
            'Hanover Golf Club',
            'Hunters Rest Golf Course',
            'Hans Merensky Hotel and Golf Estate',
            'Howick Golf Club',
            'Hoopstad Golf Club',
            'Holly Country Club',
            'Harrismith Country Club',
            'Humewood Golf Club',
            'Hankey Golf Club',
            'Heidelberg Golf Club',
            'Houghton Golf Club',
            'Hex Valley Golf Club',
            'Hermanus Golf Club',
            'Helderberg Village Golf Club',
            'Indwe Golf Club',
            'Ixopo Golf Club',
            'Irene Country Club',
            'Jagersfontein Golf Club',
            'Jan Kempdorp Golf Club',
            'Jacobsdal Golf Club',
            'Jeffreys Bay Golf Club',
            'Jackal Creek Golf Estate',
            'Kliprivier Country Club',
            'Kensington Golf Club',
            'Kwambonambi Golf Club',
            'Kirkwood Golf Club',
            'Kakamas Golf Club',
            'Kenhardt Golf Club',
            'Kestell Golf Club',
            'Kuruman Country Club',
            'King David Golf Club',
            'Knysna Golf Club',
            'Kingswood Golf Estate',
            'Koster Golf Club',
            'Klerksdorp Golf Club',
            'Koro Creek Country Club',
            'Kameeldoring Country Club',
            'Kruger Park Lodge Golf Club',
            'Kriel Golf Club',
            'Kinross Golf Club',
            'Komatipoort Golf Club',
            'Kokstad Golf Club',
            'Kloof Country Club',
            'Kilbarchan Golf Club',
            'Kimberley Golf Club',
            'Kroonstad Country Club',
            'Kroonstad Correctional Services Golf Club',
            'Koffiefontein Golf Club',
            'Kragga Kamma Golf Club',
            'Kempton Park Golf Club',
            'Kyalami Country Club',
            'Krugersdorp Golf Club',
            'Killarney Country Club',
            'Komga Sports Club',
            'King Williams Town Golf Club',
            'Kei Mouth Country Club',
            'Katberg Eco Golf Course',
            'Kuilsrivier Golf Club',
            'Kleinmond Golf Club',
            'Legend Golf and Safari Resort',
            'Lizard Point Golf Estate',
            'Leeudoringstad Golf Club',
            'Loeriesfontein Golf Club',
            'Laingsburg Golf Club',
            'Lady Grey Golf Club',
            'Lions Rock Golf Lodge',
            'Langkloof Golf Club',
            'Le Grand George Golf Course',
            'Lime Acres Golf Club',
            'Linksfield Golf Club',
            'Ladismith Golf Club',
            'Lost City Golf Club',
            'Lichtenburg Golf Club',
            'Leopard Park Golf Club',
            'Landboukollege Golf Club',
            'Louis Trichardt Golf Club',
            'Lydenburg Golf Club',
            'Ladysmith Country Club',
            'Lindley Golf Club',
            'Ladybrand Sports Club',
            'Leeuwkop Golf Club',
            'Lutzville Golf Club',
            'Langebaan Country Estate',
            'Lambertsbaai Golf Club',
            'Leopard Creek Country Club',
            'Millvale Golf Estate',
            'Mooi River Country Club',
            'Maidstone Golf Club',
            'Morningside Farm Golf Club',
            'Monks Cowl Country Club',
            'Matatiele Golf Club',
            'Metropolitan Golf Club',
            'Morgenzon Golf Club',
            'Marble Hall Golf Club',
            'Maccauvlei Golf Club',
            'Middelburg Golf Club',
            'Maclear Country Club and Golf Estate',
            'Monzi Golf Club',
            'Mowbray Golf Club',
            'Milnerton Golf Club',
            'Mossel Bay Golf Club',
            'Montagu at Fancourt',
            'Mooinooi Golf Club',
            'Magalies Park Country Club',
            'Mogol Golf Club',
            'Messina Golf Club',
            'Middelburg Country Club',
            'Malelane Golf Club',
            'Mzingazi Golf Estate',
            'Mtunzini Country Club',
            'Mount Edgecombe Country Club',
            'Melmoth Golf Club',
            'Maritzburg Golf Club',
            'Margate Country Club',
            'Mandini Sports Club',
            'Magersfontein Memorial Golf Club and Country Estate',
            'Marquard Golf Club',
            'Modderfontein Golf Club',
            'Meyerton Golf Club',
            'Mthatha Country Club',
            'Molteno Country Club',
            'Moorreesburg Golf Club',
            'Montagu Golf Club',
            'Malmesbury Golf Club (Mount Royal Golf and Country Estate)',
            'Noupoort Golf Club',
            'Naboomspruit Golf Club',
            'Nelspruit Golf Club',
            'Noodsberg Country Club',
            'Newcastle Golf Club',
            'Nigel Golf Club',
            'Outeniqua at Fancourt',
            'Orkney Golf Club',
            'Ohenimuri Country Club',
            'Orangedene Country Club',
            'Oudtshoorn Golf Club',
            'Oubaai Golf Resort and Spa',
            'Ottosdal Golf Club',
            'Oppenheimer Park Golf Club',
            'Observatory Golf Club',
            'Papwa Sewgolum Golf Course',
            'Pezula Championship Golf Course',
            'Prieska Golf Club',
            'Pullenshope Golf Club',
            'Petrus Steyn Golf Club',
            'Prince Albert Golf Club',
            'Pilgrims Rest Golf Club',
            'Parow Golf Club',
            'Plettenberg Bay Country Club',
            'Pinnacle Point Golf Club',
            'Potchefstroom Country Club',
            'Pecanwood Golf and Country Club',
            'Polokwane Golf Club',
            'Piet Retief Country Club',
            'Prince\'s Grant Golf Estate',
            'Port Shepstone Country Club',
            'Port Edward Country Club',
            'Pongola Golf Club',
            'Paulpietersburg Country Club',
            'Pretoria Golf Club',
            'Pretoria Country Club',
            'Pebble Rock Golf Club',
            'Parys Golf Club',
            'Port Elizabeth Golf Club',
            'Pollak Park Golf Club',
            'Parkview Golf Club',
            'Porterville Golf Club',
            'Piketberg Golf Club',
            'Pearl Valley Golf & Country Estate',
            'Paarl Golf Club',
            'Queenstown Golf Club',
            'Reivilo Golf Club',
            'Riversdale Golf Club',
            'Royal Johannesburg and Kensington Golf Club',
            'Reading Country Club',
            'Reitz Golf Club',
            'Richmond Country Club',
            'Robertson Golf Club',
            'Richmond Golf Club',
            'Royal Cape Golf Club',
            'Rondebosch Golf Club',
            'Rustenburg Golf Club',
            'Royal Northland Golf Club',
            'Rooiberg Golf Club',
            'Royal Port Alfred Golf Club',
            'Royal Oak Country Club',
            'Riviera on Vaal Country Club',
            'Roodepoort Country Club',
            'Randpark Golf Club',
            'Randfontein Golf and Country Club',
            'Riviersonderend Golf Club',
            'Springs Golf Club',
            'Springbok Golf Club',
            'Steynsberg Golf Club',
            'Sedibeng Country Club',
            'Swartklip Golf Club',
            'Saldanha Military Golf Club',
            'Soutpansberg Golf Club',
            'Summerfield Golf Club',
            'Saint Francis Bay Golf Club',
            'Shelley Point Golf Club',
            'Stella Golf Club',
            'Sani Pass Golf Club',
            'Smithfield Golf Club',
            'Schoeman Park Golf Club',
            'Schweizer Reneke Golf Club',
            'Sutherland Golf Club',
            'Strand Golf Club',
            'Steenberg Golf Club',
            'Somerset West Golf Club',
            'Simon\'s Town Country Club',
            'Stilbaai Golf Club',
            'Simola Golf and Country Estate',
            'Seasons Eco Golf Estate',
            'Sannieshof Golf Club',
            'Sandy Lane Golf Club',
            'Standerton Country Club',
            'Skukuza Golf Club',
            'Sabie Country Club',
            'Sabi River Bungalows Golf Club',
            'Saint Cathryn\'s Golf Estate',
            'Simbithi Country Club',
            'Southbroom Golf Club',
            'Selborne Country Club',
            'Scottburgh Golf Club',
            'San Lameer Country Club',
            'Sakabula Golf Club',
            'Silver Lakes Golf and Country Club',
            'Services Golf Club',
            'Sandonia Golf Club',
            'Sishen Golf Club',
            'Senekal Golf Club',
            'Sand River Golf Club',
            'Stafford Hill Golf and Polo Estate',
            'Somerset East Golf Club',
            'Shark River Golf Club',
            'State Mines Country Club',
            'Serengeti Golf and Wildlife Estate',
            'Saps Mechanical School Golf Club',
            'Soweto Country Club',
            'Southdowns Country Club',
            'Stutterheim Country Club',
            'Swellendam Golf Club',
            'Stellenbosch Golf Club',
            'St Francis Links',
            'The Club at Steyn City',
            'The Links at Fancourt',
            'Tsitsikamma Coastal Golf Estate',
            'Theunissen Golf Club',
            'Tweespruit Golf Club',
            'Tzaneen Country Club',
            'Thabazimbi Golf Club',
            'Tweefontein Golf Club',
            'Tempe Golf Club',
            'The Lake Club - Benoni',
            'The Country Club Johannesburg',
            'The River Club',
            'Theewaterskloof Golf Club',
            'Ulco Golf Club',
            'Upington Golf Club',
            'Uniondale Golf Club',
            'University of Limpopo Golf Club',
            'Utrecht Country Club',
            'Underberg Country Club',
            'Umkomaas Golf Club',
            'Umhlali Country Club',
            'Umfolozi Golf Club',
            'Umdoni Park Golf Club',
            'Uitenhage Golf Club',
            'Vredenburg Golf Club',
            'Venterspost Golf Club',
            'Victoria West Golf Club',
            'Victoria Country Club',
            'Vrede Golf Club',
            'Vryburg Golf Club',
            'Ventersdorp Golf Club',
            'Volksrust Golf Club',
            'Vryheid Golf Club',
            'Vaal de Grace Golf Estate',
            'Viljoenskroon Golf Club',
            'Vredendal Golf Club',
            'Waterford Golf and River Estate',
            'Wellington Golf Club',
            'Willowmore Golf Club',
            'Westminster Golf Club',
            'Wedgewood Park Country Club',
            'Woodhill Country Club',
            'Windsor Park Golf Course',
            'Walker Park Golf Club',
            'Williston Golf Club',
            'Westlake Golf Club',
            'Wolmaransstad Golf Club',
            'Witbank Golf Club',
            'White River Country Club',
            'Wild Coast Sun Country Club',
            'Wingate Park Country Club',
            'Waterkloof Golf Club',
            'Whites Golf Club',
            'Wesselsbron Golf Club',
            'Walmer',
            'Waterpan Golf Club',
            'Wanderers Golf Club',
            'West Bank Golf Club',
            'Worcester Golf Club',
            'Zwartenbosch Golf and Lifestyle Estate',
            'Zeerust Country Club',
            'Zebula Golf Estate and Spa',
            'Zebediela Country Club',
            'Zimbali Country Club',
            'Zwartkop Country Club',
            'Zastron Golf Club',
        ];

        DB::table('golf_courses')->insert(
            collect($clubs)->map(fn ($name) => ['name' => $name])->toArray()
        );
    }
}
